name: Build and Test React Application

# Controls when the action will run. 
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [ main ]
  # Triggers the workflow on pull request events for any branch
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Install backend dependencies and start the backend server
      - name: Start backend server
        run: |
          cd a3_backend
          npm install
          node app.js

      # Install frontend dependencies and build the frontend
      - name: Build and start frontend
        run: |
          cd a2_frontend
          npm install
          npm run build --if-present
          npm run test
