name: Build and Test React Application

# Controls when the action will run. 
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [ main ]
  # Triggers the workflow on pull request events for any branch
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 19.x, 20.x]
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Install backend dependencies and start the backend server
      # Step 1: Install backend dependencies
      - name: Install backend dependencies
        run: npm run install-server
#
#      # Step 2: Start the backend server
#      - name: Start backend server
#        run: timeout 30s npm run start-server

      # Step 3: Install frontend dependencies
      - name: Install frontend dependencies
        run: npm run install-client

      # Step 4: Build the frontend
      - name: Build frontend
        run: npm run build-client

      # Step 5: Test the frontend
      - name: Test frontend
        run: npm run test-client
